name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: "v1.28.0"
          kubernetes version: "v1.25.4"
          github token: ${{secrets.GITHUB_TOKEN}}
      - run: pip install pyyaml
      - run: curl https://skupper.io/install.sh | sh
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: ./plano test
